# Generated by Django 5.2.6 on 2025-09-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_print', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
